### PR TITLE
RTMP流转发（Forward）通过url来指定

### PR DESCRIPTION
**Pull request by daozhao**
RTMP流转发（Forward）通过url来指定#53

使用方式，配置文件不需要额外配置。
推送的时候可以在app中添加forward参数。暂时只支持在app中添加参数。
例如：
方式一：添加forward ip与端口
推送地址： `rtmp://192.168.2.170:1935/myapp?forward=192.168.2.170:19350/mystream` 
服务器会自动把流推送到服务器192.168.2.170:19350上。
观看forward 地址:`rtmp://192.168.2.170:19350/myapp/mystream` 播放流。
观看源地址:`rtmp://192.168.2.170:1935/myapp/mystream`
方式二：添加forward 完整地址
推送地址：` rtmp://192.168.2.170:1935/myapp?forward=rtmp%3A%2F%2F192%2E168%2E2%2E170%3A19350%2Fyapp%2Fystream/mystream `
或者
`rtmp://192.168.2.170:1935/myapp...forward...rtmp%3A%2F%2F192%2E168%2E2%2E170%3A19350%2Fyapp%2Fystream/mystream`
服务器会自动按照地址`rtmp://192.168.2.170:19350/yapp/ystream` 推送上服务器。
观看forward地址`rtmp://192.168.2.170:19350/yapp/ystream `
观看源地址` rtmp://192.168.2.170:1935/myapp/mystream`

另外注意forward完整地址需要对地址进行uri编码，可以使用objs/research/librtmp/srs_rtmp_uri_encode工具进行编码。示范uri编码程序在trunk/research/librtmp/srs_rtmp_uri_encode.c.

### CODE REVIEW

**Comment by winlinvip** [comment]
Why do we need to specify the forward address when connecting?

`TRANS_BY_GPT3`

**Comment by daozhao** [comment]
Actually, I just referenced your vhost where the parameters are passed on the connect. Actually, I also find it strange. Usually, it is better to add the forward address at the end of the address.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Why not specify these parameters in the configuration file?

`TRANS_BY_GPT3`

**Comment by daozhao** [comment]
https://github.com/simple-rtmp-server/srs/issues/53


This makes it more convenient to change whether to forward the stream at any time.

Currently, we have a use case where most of the streams only need to be viewed on the local network. They do not need to be viewed on the internet. However, sometimes certain playback sources need to be played on the internet. If this forwarding is configured through a config file, it is not very flexible.

Additionally, if authentication is required when using a third-party CDN, the authentication information needs to be included in the URL. This makes it very inflexible to configure through a configuration file.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Authentication information should be placed in the URL because it often changes.
However, vhost definitely does not need to change frequently.
If vhost is placed in the URL, the player needs to trigger a forward. This behavior is also new and may not be very suitable for open source.
Therefore, if you can change it to write vhost in the configuration, I can merge it into SRS. Please consider it, thank you for submitting the code~

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
If you think it's appropriate, you can support adding vhost information in the foward, submit a new pull request, I have closed this for now.
You're doing great, keep it up~

`TRANS_BY_GPT3`

**Pull request closed without merging**
